notifications:
  email: never
language: python
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required    
      python: 3.4_with_system_site_packages
    - os: osx
before_install:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get update; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install -y xvfb python3-pyqt5 python3-pyqt5.qtmultimedia; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then pip install PyQt5
deploy:
  provider: pypi
  user: mandeepb
  password:
    secure: !!binary |
      RE9HY2ViZEpaOStYQ2NIWUNUQzBnSXh1VHkwK2tLS0ZGOGJPb00xcGkvNldBRCtoUXBKd2xBTUZZ
      WjBoYy9JYlpsN015VWNwaUluMHdlTys2ejF1RXN6TEYxVFZPSlkxaHVrcGwyUmJqVjVOeHRpQWhM
      TFFKazFwZHVkamZyTlpKS3p0U2RWcjZPT2FEbEhVYnpWWjVlSFFGSXJyc2lJVDRwWjA5OU1DUFcz
      cXBxM2dSWlJyTzQwZ0xkb2plRThxak9qVnFjdndIMTRLQWhhcEhRdHd5NVB4VWxMekt6ZnJSbTlF
      V0JDZkFhNzhuN29UNTZETlg5cnRCZVROTTlOZFJkRENSRldRcVBEMzlJRjh3WFl3aCs3S2xQUm5h
      RUNQajBOK1BRUG5RWVphVnV3Zks5QVphdnFLeDZtSlMrUWs4Qi9KR3NreEZRVHBONDRtL3I3VnlH
      TWxveTZISkhVek9VdERZOVhFbFdvcXJhclc2a0ZvdHk2bDNhRllnM1FhZzdYRlNQUjRONFVEOGpL
      OENvL3VLNWtUWnkwZy9EODNKdDA5OTFodXF5eXZmK3ZvdlBzTS81TmxsN1NWSEVHVFhNMXpxVlY4
      Q1JXWitqYjRPc2VFOEU0Y3h0SEgvbjhSSEtEOGRpTmhSWm0xTFNhbUo5WE5YZUhYVDhFYS93MjJD
      OU5lNENsK0gvWDcxTk5VN2FWemp4ZUhReEdLTzBKZE5wYkR0dzRZYndiWkR1RWZkRFp6bGFRN3kr
      YWhxOXkyNnFHejdRZHZxVGp1VEU3QVJwcXljN2pieHBCYnQwZTdzMndJTnZ6ZkpPd2lIVk41QzMx
      MUN1UVd1bEs5eFdQVmRmbTArdmpqcVBIUXhOZXVONnpXMnUxOThXdHR1bU95d3k4MytHZDBsWHc9
  true:
    branch: master
  distributions: "sdist bdist_wheel"
install:
  - python setup.py install
  - pip install coverage
  - pip install coveralls
  - pip install pytest
  - pip install pytest-qt
  - pip install pytest-mock
  - pip install pytest-cov
  - pip install pytest-xvfb
  - pip install pytest-faulthandler
script:
  - py.test -s -v -x --cov=./
after_success:
  - coveralls