after_success:
- coveralls
before_install:
- sudo apt-get update
- sudo apt-get install -y xvfb python3-pyqt5 python3-pyqt5.qtmultimedia
deploy:
  user: mandeepb
  provider: pypi
  true:
    branch: master
  password:
    secure: AGAJqxkakDawczssi9A6ndL0JD1gX+rNnlMq3C9fjRb1ZdXYjY77hB4R2Xwjly3D70LYPCg+uug8BgoBINfBH32SM1NnY2uiHfb2nUFECL8tsbdo28KMlMIuB0qAszYE4yg1h1M02ZrGSZQoMZtUiZgbsFfBJnKsdwP29JByvVRKQ0BmVIny35O82V1JtAp8K8IxKIhn2Kw7REcKo4o5D9vZScsyIn+zE40ZVT7DOlykXt7IfFgFQdP12bYfXLREKuHswTEAWCWb1oG3B+mOUwM4l1kBHx+LDMnvKaJ4UYW1kqdCLcf1y6b39D7ynHyWKnjM0ynEk1iS6S6kA4YeOp/LQdvBLN+iumVTEGw7GeWD+LrSNOBYgkPf3Bgys0GGAZEIcRc1/aI9r1xEKkYyj3eqhJX7rRanf2bcFusgig6onMSv/XeB/kxtW4YfxpfXl6NDmt0wVOvAfGHf4FBBRj5A/u2gpBXiSw276DOd1dSPIYvGduzpCas+TrxuT64v6UrhmA4fDJAxFx8xNOtnU2p73vjTOrTYomHJghnU7Ei3pwirlWHuvXaSYfWFy+BchXKumsRyZs9n8YISBr2BG+LQLGczXxbc6DvnsxkShVQFJv33e67ntW5tfZ0PdfgIqO3cpBLT/DKYzYXeyA4f0vw2al28Gj/5OzywNd0C4rw=
  distributions: sdist bdist_wheel
dist: trusty
group: deprecated-2017Q2
install:
- python setup.py install
- pip install coverage
- pip install coveralls
- pip install pytest
- pip install pytest-qt
- pip install pytest-mock
- pip install pytest-cov
- pip install pytest-xvfb
- pip install pytest-faulthandler
language: python
notifications:
  email: false
python: 3.4_with_system_site_packages
script:
- pytest -v --cov=. --cov-report term-missing
sudo: required
