language: python
python:
  - "3.3_with_system_site_packages"
  - "3.4_with_system_site_packages"
  - "3.5_with_system_site_packages"
sudo: required
dist: trusty
notifications:
  email: false
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install -y xvfb python3-pyqt5 python3-pyqt5.qtmultimedia
  - sudo apt-get install -y libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev
install:
  - python setup.py install
  - pip install coverage
  - pip install coveralls
  - pip install codecov
  - pip install pytest
  - pip install pytest-qt
  - pip install pytest-mock
  - pip install pytest-cov
  - pip install pytest-xvfb
  - pip install pytest-faulthandler
script:
  - py.test -s -v --cov=./
after_success:
  - coveralls
  - codecov