environment:
  matrix:
      - PYTHON: "C:\\Python35-x64"
        PYTHON_VERSION: "3.5.0"
        PYTHON_ARCH: "64"
version: 1.0.{build}
branches:
  only:
    - master
install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "pip install --disable-pip-version-check --user --upgrade pip"
  - "python setup.py install"
  - "pip install coverage"
  - "pip install coveralls"
  - "pip install pytest"
  - "pip install pytest-qt"
  - "pip install pytest-mock"
  - "pip install pytest-cov"
  - "pip install pytest-xvfb"
  - "pip install pytest-faulthandler"
test_script:
- "py.test -s -v -x --cov=./"
after_test:
- "coveralls"