environment:
  matrix:
      - PYTHON: "C:\\Python35-x64"
        PYTHON_VERSION: "3.5.0"
        PYTHON_ARCH: "64"

version: 1.0.{build}

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install --upgrade pip"
  - "pip install PyQt5"
  - "pip install coverage"
  - "pip install pytest"
  - "pip install pytest-qt"
  - "pip install pytest-mock"
  - "pip install pytest-cov"
  - "pip install pytest-xvfb"
  - "pip install pytest-faulthandler"
  - "pip install natsort"
  - "pip install importlib_resources"

build_script:
  - "%CMD_IN_ENV% python setup.py install"

test_script:
  - "%CMD_IN_ENV% py.test -s -v -x --cov=./"
